require("settings")
require("keymaps")
require("plugin.packerConfig")
require("plugin.lsp")
require("plugin.lsp.completion")
require("plugin.treeSitterConfig")
require("plugin.tsRainbowConfig")
require("plugin.telescopeConfig")
require("plugin.luaLineConfig")
require("plugin.barbarConfig")
require("keymaps.barbar")
require("plugin.nvimTreeConfig")
require("plugin.gitSignsConfig")
require("plugin.notifyConfig")
require("plugin.colorizerConfig")
require("plugin.commentConfig")
require("plugin.indentBlankLineConfig")

-- print("hello,sucka!!")

