require("gui") -- statusline, tabs, notify, theme, etc.
require("settings")
require("keymaps")
require("plugin.packerConfig")
--require("plugin.notifyConfig")
--require("plugin.barbarConfig")
require("keymaps.barbar")
--require("plugin.luaLineConfig")
require("plugin.nvimTreeConfig")
require("plugin.lsp")
require("plugin.lsp.nvim-cmp")
require("plugin.lsp.lspkind")
require("plugin.treeSitterConfig")
require("plugin.tsRainbowConfig")
require("plugin.telescopeConfig")
require("plugin.gitSignsConfig")
--require("plugin.undoTreeConfig")
require("plugin.colorizerConfig")
require("plugin.commentConfig")
--require("plugin.indentBlankLineConfig")
--require("plugin.oneDarkConfig")
--require("lsp")
-- print("hello,sucka!!")

