 require("gui.lualine_nvim-conf")
 require("gui.barbar_nvim-conf")
require("gui.nvim-tree-conf")
require("gui.indent-blankline_nvim-conf")
require("gui.onedark_nvim-conf")
require("gui.undotree-conf")
require("gui.nvim-notify-conf")
